kind: Service
apiVersion: v1
metadata:
  name: metadata-envoy
  labels:
    app: metadata-envoy
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 9090
      protocol: TCP
      name: md-envoy
  selector:
    app: metadata-envoy
    release: {{ .Release.Name }}