apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: pipeline-api
    release: {{ .Release.Name }}
  name: pipeline-api
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/log
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - list
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - "kubeflow.org"
  resources:
  - viewers
  verbs:
  - create
  - get
  - list
  - watch
  - delete
- apiGroups:
  - "argoproj.io"
  resources:
  - workflows
  verbs:
  - get
  - list
