apiVersion: v1
kind: Service
metadata:
  name: pipeline-api
  labels:
    app: pipeline-api
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
    - name: grpc
      port: 8887
      protocol: TCP
      targetPort: grpc
  selector:
    app: pipeline-api
    release: {{ .Release.Name }}