apiVersion: v1
kind: Service
metadata:
  name: visualization-server
  labels:
    app: visualization-server
    release: {{ .Release.Name }}
spec:
  ports:
    - name: http
      port: 8888
      protocol: TCP
      targetPort: http
  selector:
    app: pipeline-ui
    release: {{ .Release.Name }}