apiVersion: v1
kind: Service
metadata:
  labels:
    app: ml-pipeline-ui
  name: ml-pipeline-ui
spec:
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
    # Optional: Specify a nodePort in the range (default range is 30000-32767)
    nodePort: 30081
  selector:
    app: ml-pipeline-ui
