apiVersion: v1
kind: ConfigMap
metadata:
  name: metadata-grpc
  labels:
    app: metadata-grpc
    release: {{ .Release.Name }}
data:
  MYSQL_DATABASE: '{{ .Values.mysql.auth.database | default "kubeflow"}}'
  MYSQL_HOST: '{{ .Values.mysql.server.host | default "mysql"}}'
  MYSQL_PORT: '{{ .Values.mysql.server.port | default "3306"}}'