apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-grpc
  labels:
    app: metadata-grpc
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-grpc
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: metadata-grpc
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.metadata.grpc.securityContext | nindent 12 }}
      containers:
      - name: metadata-grpc
        image: {{ .Values.metadata.grpc.image }}
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              name: metadata-grpc
              key: MYSQL_HOST
        - name: MYSQL_PORT
          valueFrom:
            configMapKeyRef:
              name: metadata-grpc
              key: MYSQL_PORT
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: metadata-grpc
              key: MYSQL_DATABASE
        - name: DBCONFIG_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: DBCONFIG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        command: ["/bin/metadata_store_server"]
        args: ["--grpc_port=8080",
               "--mysql_config_database=$(MYSQL_DATABASE)",
               "--mysql_config_host=$(MYSQL_HOST)",
               "--mysql_config_port=$(MYSQL_PORT)",
               "--mysql_config_user=$(DBCONFIG_USER)",
               "--mysql_config_password=$(DBCONFIG_PASSWORD)",
               "--enable_database_upgrade=true"
                ]
        resources:
          {{- toYaml .Values.metadata.envoy.resources | nindent 12 }}
        ports:
        - containerPort: 8080
          name: grpc-api
        livenessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 2
        readinessProbe:
          tcpSocket:
            port: grpc-api
          initialDelaySeconds: 10
          periodSeconds: 2
          timeoutSeconds: 2
      serviceAccountName: pipelines-grpc
      {{- with .Values.metadata.envoy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metadata.grpc.priorityClassName }}
      priorityClassName: {{ .Values.metadata.grpc.priorityClassName }}
      {{- end }}
      {{- with .Values.metadata.grpc.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metadata.grpc.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}