apiVersion: v1
kind: Service
metadata:
  name: metadata-grpc
  labels:
    app: metadata-grpc
    release: {{ .Release.Name }}
spec:
  ports:
    - name: grpc-api
      port: 8080
      targetPort: grpc-api
      protocol: TCP
  selector:
    app: metadata-grpc
    release: {{ .Release.Name }}