apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: viewers.kubeflow.org
  labels:
    app: viewer-crd
    release: {{ .Release.Name }}
spec:
  group: kubeflow.org
  names:
    kind: Viewer
    plural: viewers
    shortNames:
      - vi
  scope: Namespaced
  versions:
    - name: v1beta1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cronSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer