apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: viewer-crd
  labels:
    app: viewer-crd
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: viewer-crd
subjects:
  - kind: ServiceAccount
    name: viewer-crd
    namespace: {{ .Release.Namespace }}