apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: viewer-crd
  labels:
    app: viewer-crd
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - '*'
    resources:
      - deployments
      - services
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - kubeflow.org
    resources:
      - viewers
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete