apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-workflow-controller
  annotations:
    internal.kpt.dev/upstream-identifier: 'apps|Deployment|default|workflow-controller'
  labels:
   app: workflow-controller
spec:
  selector:
    matchLabels:
     app: workflow-controller
  template:
    metadata:
      labels:
       app: workflow-controller
    spec:
      serviceAccountName: argo
      containers:
        - name: argo-workflow-controller
          image: "{{ .Values.argo.argoworkflowcontroller.image }}"
          command:
            - workflow-controller
          args:
            - --configmap
            - workflow-controller-configmap
            - --executor-image
            - "{{ .Values.argo.executor.image }}"

          env:
          - name: LEADER_ELECTION_IDENTITY
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          ports:
            - name: metrics
              containerPort: 9090
            - containerPort: 6060
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 6060
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        {{- toYaml .Values.argo.securityContext | nindent 12 }}
      {{- with .Values.argo.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.argo.priorityClassName }}
      priorityClassName: {{ .Values.argo.priorityClassName }}
      {{- end }}
      {{- with .Values.argo.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.argo.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}