apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scheduled-workflow
  labels:
    app: scheduled-workflow
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - create
      - get
      - list
      - watch
      - update
      - patch
      - delete
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
      
