apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduled-workflow
  labels:
    app: scheduled-workflow
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduled-workflow
subjects:
  - kind: ServiceAccount
    name: scheduled-workflow
    namespace: {{ .Release.Namespace }}