apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-visualizationserver
  labels:
    app: ml-pipeline-visualizationserver
spec:
  selector:
    matchLabels:
      app: ml-pipeline-visualizationserver
  template:
    metadata:
      labels:
        app: ml-pipeline-visualizationserver
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      securityContext:
        {{- toYaml .Values.pipeline.visualisationserver.securityContext | nindent 12 }}
      containers:
        - image: {{ .Values.pipeline.visualisationserver.image }}
          imagePullPolicy: IfNotPresent
          name: ml-pipeline-visualizationserver
          resources:
            {{- toYaml .Values.pipeline.visualisationserver.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 8888
          readinessProbe:
            exec:
              command:
                - wget
                - -q # quiet
                - -S # show server response
                - -O
                - "-" # Redirect output to stdout
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            exec:
              command:
                - wget
                - -q # quiet
                - -S # show server response
                - -O
                - "-" # Redirect output to stdout
                - http://localhost:8888/
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 2
      {{- with .Values.pipeline.visualisationserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.pipeline.visualisationserver.priorityClassName }}
      priorityClassName: {{ .Values.pipeline.visualisationserver.priorityClassName }}
      {{- end }}
      {{- with .Values.pipeline.visualisationserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pipeline.visualisationserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: ml-pipeline-visualizationserver
