apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: persistence-agent
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - kubeflow.org
    resources:
      - scheduledworkflows
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - patch