apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: persistence-agent
  labels:
    app: {{ .Release.Name }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: persistence-agent
subjects:
  - kind: ServiceAccount
    name: persistence-agent
    namespace: {{ .Release.Namespace }}