apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: metadata-writer
        release: {{ .Release.Name }}
    spec:
      securityContext:
        {{- toYaml .Values.metadata.writer.securityContext | nindent 12 }}
      containers:
      - name: metadata-writer
        image: {{ .Values.metadata.writer.image }}
        imagePullPolicy: Always
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: METADATA_GRPC_SERVICE_SERVICE_HOST
          value: "metadata-grpc"
        - name: METADATA_GRPC_SERVICE_SERVICE_PORT
          value: "8080"
        resources:
          {{- toYaml .Values.metadata.writer.resources | nindent 12 }}
      serviceAccountName:  metadata-writer
      {{- with .Values.metadata.writer.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metadata.writer.priorityClassName }}
      priorityClassName: {{ .Values.metadata.writer.priorityClassName }}
      {{- end }}
      {{- with .Values.metadata.writer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metadata.writer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}