apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metadata-writer
  template:
    metadata:
      labels:
        app: metadata-writer
    spec:
      securityContext:
        {{- toYaml .Values.metadata.writer.securityContext | nindent 12 }}
      containers:
      - name: metadata-writer
        image: {{ .Values.metadata.writer.image }}
        env:
        - name: NAMESPACE_TO_WATCH
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
          {{- toYaml .Values.metadata.writer.resources | nindent 12 }}
      serviceAccountName: kubeflow-pipelines-metadata-writer
      {{- with .Values.metadata.envoy.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.metadata.writer.priorityClassName }}
      priorityClassName: {{ .Values.metadata.writer.priorityClassName }}
      {{- end }}
      {{- with .Values.metadata.writer.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metadata.writer.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}