apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: metadata-writer
subjects:
- kind: ServiceAccount
  name: metadata-writer
  namespace: {{ .Release.Namespace }}