apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metadata-writer
  labels:
    app: metadata-writer
    release: {{ .Release.Name }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
  - update
  - patch