executor:
  emissary: true

managedstorage:
  enabled: false

minio:
  ak: LEINAOYUNOS
  sk: wJalrXUtnFEMI/K7MDENG/bPxRfiCYLEINAOYUNKEY
  endpoint: miniogw-dev2.cnbita.com
  port: 11443
  bucketName: mlpipeline
  pipelinePath: pipelines
  insecure: true

mysql:
  server:
    host: 192.168.13.88
    port: 3306
  auth:
    database: metadb
    username: root
    password: 123456
    existingSecret: mysql-secret
    
argo:
  # Argo workflow controller
  executor:
    image: registry.cnbita.com:5000/kubeflow-pipelines/argoexec:v3.3.10-license-compliance
  argoworkflowcontroller:
    image: registry.cnbita.com:5000/kubeflow-pipelines/workflow-controller:v3.3.10-license-compliance
  securityContext: {}
  resources: {}
  nodeSelector: {}
  priorityClassName: {}
  affinity: {}
  tolerations: {}

metadata:
  # Metadata services.
  envoy:
    # Metadata envoy service.
    image: registry.cnbita.com:5000/kubeflow-pipelines/metadata-envoy:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  grpc:
    # Metadata grpc service.
    image: registry.cnbita.com:5000/kubeflow-pipelines/ml_metadata_store_server:1.14.0
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  writer:
    # Metadata writer service.
    image: registry.cnbita.com:5000/kubeflow-pipelines/metadata-writer:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
    
pipeline:
  # Persistence agent component
  persistenceagent:
    image: registry.cnbita.com:5000/kubeflow-pipelines/persistenceagent:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  api:
    # Pipeline api server.
    image: registry.cnbita.com:5000/kubeflow-pipelines/api-server:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  ui:
    # Pipeline frontend.
    image: registry.cnbita.com:5000/kubeflow-pipelines/frontend:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
    ingress:
      tls:
        certsSecret: null
  scheduledworkflow:
    # Pipeline scheduled workflow - allows for scheduling pipeline runs periodically.
    image: registry.cnbita.com:5000/kubeflow-pipelines/scheduledworkflow:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  viewer:
    # Viewer crd.
    image: registry.cnbita.com:5000/kubeflow-pipelines/viewer-crd-controller:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}
  visualisationserver:
    # Creates visualisations and plots to display pipeline run results and metrics.
    image: registry.cnbita.com:5000/kubeflow-pipelines/visualization-server:2.0.5
    securityContext: {}
    resources: {}
    nodeSelector: {}
    priorityClassName: {}
    affinity: {}
    tolerations: {}