{{- $rootPassword := randAlphaNum 42 }}
{{- $replicationPassword := randAlphaNum 42 }}
{{- $password := randAlphaNum 42 }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    
type: Opaque
data:
  username: {{ toString .Values.mysql.auth.username | default "kubeflow" | b64enc }}
  password: {{ toString .Values.mysql.auth.password | default $password | b64enc }}