apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-ui
  labels:
    app: pipeline-ui
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pipeline-ui
subjects:
  - kind: ServiceAccount
    name: pipeline-ui
    namespace: {{ .Release.Namespace }}