apiVersion: v1
kind: Service
metadata:
  name: pipeline-ui
  labels:
    app: pipeline-ui
    release: {{ .Release.Name }}
spec:
  ports:
    - port: 80
      targetPort: http
  selector:
    app: pipeline-ui
    release: {{ .Release.Name }}