{{- $rootPassword := randAlphaNum 42 }}
{{- $replicationPassword := randAlphaNum 42 }}
{{- $password := randAlphaNum 42 }}
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  labels:
    app: mysql
    release: {{ .Release.Name }}
type: Opaque
data:
  mysql-username: {{ toString .Values.mysql.auth.username | default "kubeflow" | b64enc }}
  mysql-password: {{ toString .Values.mysql.auth.password | default $password | b64enc }}